spring:
  application:
    name: franquicias
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/neondb}
    username: ${SPRING_R2DBC_USERNAME:neondb_owner}
    password: ${SPRING_R2DBC_PASSWORD:default}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
